// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Radio_Search.Importer.Canada.Data;

#nullable disable

namespace Radio_Search.Importer.Canada.Data.Migrations
{
    [DbContext(typeof(CanadaImporterContext))]
    partial class CanadaImporterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Canada_Importer")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.History.ImportHistory", b =>
                {
                    b.Property<Guid>("ImportHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FileHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ImportRowCount")
                        .HasColumnType("int");

                    b.Property<int>("SkippedRowCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ImportHistoryID");

                    b.ToTable("ImportHistory", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.AnalogDigital", b =>
                {
                    b.Property<string>("AnalogDigitalID")
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AnalogDigitalID");

                    b.ToTable("AnalogDigital", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.AntennaPattern", b =>
                {
                    b.Property<string>("AntennaPatternID")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AntennaPatternID");

                    b.ToTable("AntennaPatterns", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.AuthorizationStatus", b =>
                {
                    b.Property<string>("AuthorizationStatusID")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthorizationStatusID");

                    b.ToTable("AuthorizationStatuses", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.CommunicationType", b =>
                {
                    b.Property<string>("CommunicationTypeID")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("CommunicationTypeID");

                    b.ToTable("CommunicationTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.ConformityFrequencyPlan", b =>
                {
                    b.Property<string>("ConformityFrequencyPlanID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ConformityFrequencyPlanID");

                    b.ToTable("ConformityFrequencyPlans", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.CongestionZoneType", b =>
                {
                    b.Property<string>("CongestionZoneTypeID")
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("CongestionZoneTypeID");

                    b.ToTable("CongestionZoneTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.FiltrationInstalledType", b =>
                {
                    b.Property<string>("FiltrationInstalledTypeID")
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("FiltrationInstalledTypeID");

                    b.ToTable("FiltrationInstalledTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.ITUClassType", b =>
                {
                    b.Property<string>("ITUClassTypeID")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ITUClassTypeID");

                    b.ToTable("ITUClassTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.LicenseRecord", b =>
                {
                    b.Property<string>("LicenseRecordID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AnalogCapacityChannels")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<string>("AnalogDigitalID")
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal?>("AntennaGainDbi")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<string>("AntennaManufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AntennaModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AntennaPatternID")
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("AntennaStructureHeightM")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<string>("AuthorizationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizationStatusID")
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("AzimuthMainLobeDeg")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<decimal?>("BeamwidthDeg")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<string>("CallSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunicationTypeID")
                        .HasColumnType("nvarchar(5)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ConformityToFrequencyPlanConformityFrequencyPlanID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CongestionZoneTypeID")
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesignationOfEmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DigitalCapacityMbps")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<string>("FiltrationInstalledTypeID")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("FrequencyAllocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FrequencyMHz")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<decimal?>("FrontToBackRatioDb")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<int?>("GroundElevationM")
                        .HasColumnType("int");

                    b.Property<decimal?>("HeightAboveGroundM")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<decimal?>("HorizontalPowerW")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<string>("ITUClassOfStationITUClassTypeID")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("InServiceDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternationalCoordinationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("LicenceTypeLicenseTypeID")
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("LicenseeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("ModulationTypeID")
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("NumberOfIdenticalStations")
                        .HasColumnType("int");

                    b.Property<decimal?>("OccupiedBandwidthKHz")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<string>("OperationalStatusID")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("PolarizationTypeID")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ProvinceID")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("RadiusOfOperationKm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("RegulatoryServiceID")
                        .HasColumnType("smallint");

                    b.Property<string>("RxThresholdSignalLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RxUnfadedReceivedSignalLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SatelliteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ServiceTypeID")
                        .HasColumnType("smallint");

                    b.Property<short?>("StandbyTransmitterInformationID")
                        .HasColumnType("smallint");

                    b.Property<string>("StationClassID")
                        .HasColumnType("nvarchar(5)");

                    b.Property<short?>("StationCostCategoryID")
                        .HasColumnType("smallint");

                    b.Property<string>("StationFunctionTypeID")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("StationLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("StationTypeID")
                        .HasColumnType("smallint");

                    b.Property<short?>("SubserviceTypeID")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("TotalLossesDb")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<decimal?>("TxERPdBW")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<decimal?>("TxPowerW")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("VerticalElevationAngleDeg")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.Property<decimal?>("VerticalPowerW")
                        .HasPrecision(12, 10)
                        .HasColumnType("decimal(12,10)");

                    b.HasKey("LicenseRecordID");

                    b.HasIndex("AnalogDigitalID");

                    b.HasIndex("AntennaPatternID");

                    b.HasIndex("AuthorizationStatusID");

                    b.HasIndex("CommunicationTypeID");

                    b.HasIndex("ConformityToFrequencyPlanConformityFrequencyPlanID");

                    b.HasIndex("CongestionZoneTypeID");

                    b.HasIndex("FiltrationInstalledTypeID");

                    b.HasIndex("FrequencyMHz");

                    b.HasIndex("ITUClassOfStationITUClassTypeID");

                    b.HasIndex("LicenceTypeLicenseTypeID");

                    b.HasIndex("ModulationTypeID");

                    b.HasIndex("OperationalStatusID");

                    b.HasIndex("PolarizationTypeID");

                    b.HasIndex("ProvinceID");

                    b.HasIndex("RegulatoryServiceID");

                    b.HasIndex("ServiceTypeID");

                    b.HasIndex("StandbyTransmitterInformationID");

                    b.HasIndex("StationClassID");

                    b.HasIndex("StationCostCategoryID");

                    b.HasIndex("StationFunctionTypeID");

                    b.HasIndex("StationTypeID");

                    b.HasIndex("SubserviceTypeID");

                    b.ToTable("LicenseRecords", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.LicenseRecordHistory", b =>
                {
                    b.Property<int>("LicenseRecordHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseRecordHistoryID"));

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<Guid>("ImportHistoryRecordImportHistoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JSONRepresentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseRecordID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LicenseRecordHistoryID");

                    b.HasIndex("ImportHistoryRecordImportHistoryID");

                    b.HasIndex("LicenseRecordID");

                    b.ToTable("LicenseRecordsHistory", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.LicenseType", b =>
                {
                    b.Property<string>("LicenseTypeID")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LicenseTypeID");

                    b.ToTable("LicenseTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.ModulationType", b =>
                {
                    b.Property<string>("ModulationTypeID")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ModulationTypeID");

                    b.ToTable("ModulationTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.OperationalStatus", b =>
                {
                    b.Property<string>("OperationalStatusID")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("OperationalStatusID");

                    b.ToTable("OperationStatuses", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.PolarizationType", b =>
                {
                    b.Property<string>("PolarizationTypeID")
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PolarizationTypeID");

                    b.ToTable("PolarizationTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.Province", b =>
                {
                    b.Property<string>("ProvinceID")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ProvinceID");

                    b.ToTable("Provinces", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.RegulatoryService", b =>
                {
                    b.Property<short>("RegulatoryServiceID")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RegulatoryServiceID");

                    b.ToTable("RegulatoryServices", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.ServiceType", b =>
                {
                    b.Property<short>("ServiceTypeID")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ServiceTypeID");

                    b.ToTable("ServiceTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.StandbyTransmitterInformation", b =>
                {
                    b.Property<short>("StandbyTransmitterInformationID")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StandbyTransmitterInformationID");

                    b.ToTable("StandbyTransmitterInformation", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.StationClass", b =>
                {
                    b.Property<string>("StationClassID")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StationClassID");

                    b.ToTable("StationClasses", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.StationCostCategory", b =>
                {
                    b.Property<short>("StationCostCategoryID")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StationCostCategoryID");

                    b.ToTable("StationCostCategories", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.StationFunctionType", b =>
                {
                    b.Property<string>("StationFunctionTypeID")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StationFunctionTypeID");

                    b.ToTable("stationFunctionTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.StationType", b =>
                {
                    b.Property<short>("StationTypeID")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StationTypeID");

                    b.ToTable("stationTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.SubserviceType", b =>
                {
                    b.Property<short>("SubserviceTypeID")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SubserviceTypeID");

                    b.ToTable("SubserviceTypes", "Canada_Importer");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.LicenseRecord", b =>
                {
                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.AnalogDigital", "AnalogDigital")
                        .WithMany()
                        .HasForeignKey("AnalogDigitalID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.AntennaPattern", "AntennaPattern")
                        .WithMany()
                        .HasForeignKey("AntennaPatternID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.AuthorizationStatus", "AuthorizationStatus")
                        .WithMany()
                        .HasForeignKey("AuthorizationStatusID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.CommunicationType", "CommunicationType")
                        .WithMany()
                        .HasForeignKey("CommunicationTypeID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.ConformityFrequencyPlan", "ConformityToFrequencyPlan")
                        .WithMany()
                        .HasForeignKey("ConformityToFrequencyPlanConformityFrequencyPlanID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.CongestionZoneType", "CongestionZone")
                        .WithMany()
                        .HasForeignKey("CongestionZoneTypeID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.FiltrationInstalledType", "FiltrationInstalled")
                        .WithMany()
                        .HasForeignKey("FiltrationInstalledTypeID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.ITUClassType", "ITUClassOfStation")
                        .WithMany()
                        .HasForeignKey("ITUClassOfStationITUClassTypeID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.LicenseType", "LicenceType")
                        .WithMany()
                        .HasForeignKey("LicenceTypeLicenseTypeID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.ModulationType", "ModulationType")
                        .WithMany()
                        .HasForeignKey("ModulationTypeID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.OperationalStatus", "OperationalStatus")
                        .WithMany()
                        .HasForeignKey("OperationalStatusID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.PolarizationType", "Polarization")
                        .WithMany()
                        .HasForeignKey("PolarizationTypeID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.RegulatoryService", "RegulatoryService")
                        .WithMany()
                        .HasForeignKey("RegulatoryServiceID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.ServiceType", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceTypeID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.StandbyTransmitterInformation", "StandbyTransmitterInfo")
                        .WithMany()
                        .HasForeignKey("StandbyTransmitterInformationID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.StationClass", "StationClass")
                        .WithMany()
                        .HasForeignKey("StationClassID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.StationCostCategory", "StationCostCategory")
                        .WithMany()
                        .HasForeignKey("StationCostCategoryID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.StationFunctionType", "StationFunction")
                        .WithMany()
                        .HasForeignKey("StationFunctionTypeID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.StationType", "StationType")
                        .WithMany()
                        .HasForeignKey("StationTypeID");

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.SubserviceType", "Subservice")
                        .WithMany()
                        .HasForeignKey("SubserviceTypeID");

                    b.Navigation("AnalogDigital");

                    b.Navigation("AntennaPattern");

                    b.Navigation("AuthorizationStatus");

                    b.Navigation("CommunicationType");

                    b.Navigation("ConformityToFrequencyPlan");

                    b.Navigation("CongestionZone");

                    b.Navigation("FiltrationInstalled");

                    b.Navigation("ITUClassOfStation");

                    b.Navigation("LicenceType");

                    b.Navigation("ModulationType");

                    b.Navigation("OperationalStatus");

                    b.Navigation("Polarization");

                    b.Navigation("Province");

                    b.Navigation("RegulatoryService");

                    b.Navigation("Service");

                    b.Navigation("StandbyTransmitterInfo");

                    b.Navigation("StationClass");

                    b.Navigation("StationCostCategory");

                    b.Navigation("StationFunction");

                    b.Navigation("StationType");

                    b.Navigation("Subservice");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.LicenseRecordHistory", b =>
                {
                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.History.ImportHistory", "ImportHistoryRecord")
                        .WithMany("AssociatedRecords")
                        .HasForeignKey("ImportHistoryRecordImportHistoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Radio_Search.Importer.Canada.Data.Models.License.LicenseRecord", "LicenseRecord")
                        .WithMany("History")
                        .HasForeignKey("LicenseRecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportHistoryRecord");

                    b.Navigation("LicenseRecord");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.History.ImportHistory", b =>
                {
                    b.Navigation("AssociatedRecords");
                });

            modelBuilder.Entity("Radio_Search.Importer.Canada.Data.Models.License.LicenseRecord", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
