parameters:
  - name: projectDirectory
    type: string
  - name: projectFile
    type: string
  - name: dotnetVersion
    type: string
    default: '8.x'

jobs:
  - job: BuildAndPack
    displayName: "Build and Pack Library + Tests"
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          version: ${{ parameters.dotnetVersion }}

      - task: NuGetAuthenticate@1

      - task: DotNetCoreCLI@2
        displayName: 'Restore .NET packages'
        inputs:
          command: 'restore'
          projects: ${{ parameters.projectFile }}

      - task: DotNetCoreCLI@2
        displayName: 'Build all projects (library + tests)'
        inputs:
          command: 'build'
          projects: '${{ parameters.projectDirectory }}/*.csproj'
          arguments: '--configuration Release'

      - task: DotNetCoreCLI@2
        displayName: 'Pack the library into a NuGet package'
        inputs:
          command: 'pack'
          packagesToPack: ${{ parameters.projectFile }}
          versioningScheme: byBuildNumber
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

      - publish: '$(Build.ArtifactStagingDirectory)'
        artifact: drop
