parameters:
  - name: artifactName
    type: string
    default: zipfile
  - name: azureSubscription
    type: string
    default: Radio-Search
  - name: appName
    type: string


jobs:
  - job: Deploy
    displayName: "Deploy"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    pool:
      vmImage: 'windows-latest'
    steps:
      - download: current
        artifact: ${{ parameters.artifactName }}
        displayName: 'Download Test Artifacts'

      - task: AzureFunctionApp@2
        displayName: 'Deploy Azure Function App'
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          appType: functionAppLinux
          isFlexConsumption: true
          appName: ${{ parameters.appName }}
          package: $(Pipeline.Workspace)/${{ parameters.artifactName }}/*.zip
          deploymentMethod: 'auto'