parameters:
  - name: packageArtifactName
    type: string
    default: 'lib'

jobs:
  - job: BuildAndPack
    displayName: "Build and Pack Library + Tests"
    pool:
      vmImage: 'windows-latest'
    steps:
      - download: current
        artifact: ${{ parameters.packageArtifactName }}
        displayName: 'Download Library Artifacts'

      - task: NuGetAuthenticate@1

      - task: NuGetCommand@2
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
        displayName: 'Publish package to Artifact Feed'
        inputs:
          command: 'push'
          packagesToPush: '$(Pipeline.Workspace)/${{ parameters.packageArtifactName }}/*.nupkg'
          publishVstsFeed: Byte-Force-Artifacts
          vstsFeed: Byte-Force-Artifacts