parameters:
  - name: packageArtifactName
    type: string
    default: 'lib'

jobs:
  - job: PublishPackage
    displayName: "Publish Package"
    pool:
      vmImage: 'windows-latest'
    steps:
      - download: current
        artifact: ${{ parameters.packageArtifactName }}
        displayName: 'Download Library Artifacts'

      - script: dir $(Pipeline.Workspace)/${{ parameters.packageArtifactName }}
        displayName: 'List downloaded artifacts'

      - task: NuGetAuthenticate@1

      - task: NuGetCommand@2
        displayName: 'Publish package to Artifact Feed'
        inputs:
          command: 'push'
          packagesToPush: '$(Pipeline.Workspace)/${{ parameters.packageArtifactName }}/*.nupkg'
          publishVstsFeed: 'Radio-Search'  # Ensure this feed name is correct