name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - utils/Radio-Search.Utils.MessageBroker/**

stages:
- stage: Build
  displayName: 'Build and Pack'
  jobs:
    - template: /infrastructure/pipelines/templates/build-package.yml
      parameters:
        projectDirectory: 'utils/Radio_Search.Utils.MessageBroker'
        projectFile: 'utils/Radio_Search.Utils.MessageBroker/Radio_Search.Utils.MessageBroker/Radio_Search.Utils.MessageBroker.csproj'
        dotnetVersion: '8.x'
        hasTests: false

- stage: Publish
  displayName: 'Publish the package'
  dependsOn: Build
  jobs:
    - template: /infrastructure/pipelines/templates/publish-package.yml